//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using IDC.Repository.Dapper;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace IDC.Repository.Entities.Nwcali
{ 
    /// <summary>
    /// 
    /// </summary>
[ConnectionString("Nsap4NwcaliDbContext", "Nsap4NwcaliDbContext")]
    public partial class MachineInfo 
    {
        public MachineInfo()
        {
          this.Guid= string.Empty;
          this.OrderNo= string.Empty;
          this.CreateTime= DateTime.Now;
          this.FileId= string.Empty;
        }

        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string Guid { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string OrderNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public int? Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        [Browsable(false)]
        public string FileId { get; set; }
    }
}